source 'https://rubygems.org'

gem 'cucumber', '3.0.2'
gem 'capybara', '2.18.0'
gem 'rspec'
gem 'rake'
gem 'selenium-webdriver'
gem 'pry'
gem 'kaminari'
gem 'brazilian-rails'
gem 'clipboard'
gem 'saucelabs'
gem 'rubyXL'
gem 'site_prism', '2.12'
gem 'chromedriver-helper'
gem 'rails'
gem 'capybara_table'
gem 'pg'
gem 'sqlite3'
gem 'tiny_tds'