source 'https://rubygems.org'

gem 'cucumber' 
gem 'capybara','2.18.0' #o site_prism está com um bug na versao 2.13 e só funciona
gem 'rspec'
gem 'rake'
gem 'selenium-webdriver'
gem 'pry'
gem 'kaminari'
gem 'brazilian-rails'
gem 'clipboard'
gem 'saucelabs'
gem 'rubyXL'
gem 'site_prism','2.12'
gem 'chromedriver-helper'
gem 'rails'